# Generated by Django 5.1.2 on 2024-10-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
