# Generated by Django 5.1.2 on 2024-10-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_mypost_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
